Update git-watch

diff --git a/bin/git-watch b/bin/git-watch
--- a/bin/git-watch
+++ b/bin/git-watch
@@ -1,60 +1,65 @@
 #!/bin/bash
 
-if [ -z "${1}" ]; then
-	echo "usage: git watch <user>:<branch> [<local_branch>] OR git watch pull"
-	exit
-fi
+set -eu
 
-# parse git remote information
-origin_url=$(git remote show origin | grep -m 1 -o 'git@[A-Za-z0-9._-]*:[A-Za-z0-9_-]*[A-Za-z0-9\/_-]*\.git')
+usage() {
+	echo "Usage: git watch <user>:<branch> [<local_branch>] OR git watch pull" 1>&2
+	exit 1
+}
 
-if [ -z "${origin_url}" ]; then
-	echo "origin remote url is not found"
-	exit
-fi
+main() {
+	if [ $# -le 0 ]; then
+		usage
+	fi
 
-git_url=$(echo $origin_url | cut -f1 -d":")
-git_repo=$(echo $origin_url | cut -f2- -d"/")
-
-# parse argument
-if [ "${1}" == "pull" ]; then
-	# pull style
-	local_branch=$(git rev-parse --abbrev-ref HEAD)
-
-	user=$(echo $local_branch | cut -f1 -d"/")
-	if [ -z "${user}" ]; then
-		echo "user is not found"
+	local origin_url=$(git remote get-url origin)
+	if [ -z "${origin_url}" ]; then
+		echo "origin's remote url is not found" 1>&2
 		exit
 	fi
 
-	branch=$(echo $local_branch | cut -f2 -d"/")
-	if [ -z "${branch}" ]; then
-		echo "branch not found"
-		exit
-	fi
+	local git_url=$(echo $origin_url | cut -f1 -d":")
+	local git_repo=$(echo $origin_url | cut -f2- -d"/")
 
-	# git pull
-	git pull $git_url:$user/$git_repo $branch:$local_branch
-else
-	# <user>:<branch> style
-	user=$(echo $1 | cut -f1 -d":")
-	if [ -z "${user}" ]; then
-		echo "user is not found"
-		exit
-	fi
+	if [ "$1" = "pull" ]; then
+		# pull style
+		local local_branch=$(git rev-parse --abbrev-ref HEAD)
 
-	branch=$(echo $1 | cut -f2 -d":")
-	if [ -z "${branch}" ]; then
-		echo "branch not found"
-		exit
-	fi
+		local user=$(echo $local_branch | cut -f1 -d"/")
+		if [ -z "${user}" ]; then
+			echo "user is not found"
+			exit
+		fi
 
-	if [ -n "$2" ]; then
-		local_branch=$2
+		local remote_branch=$(echo $local_branch | cut -f2- -d"/")
+		if [ -z "${remote_branch}" ]; then
+			echo "remote_branch not found"
+			exit
+		fi
+
+		git pull $git_url:$user/$git_repo $remote_branch:$local_branch
 	else
-		local_branch="${user}/${branch}"
-	fi
+		# <user>:<remote_branch> style
+		local user=$(echo $1 | cut -f1 -d":")
+		if [ -z "$user" ]; then
+			echo "user is not found"
+			exit
+		fi
 
-	# git fetch and checkout
-	git fetch $git_url:$user/$git_repo $branch:$local_branch && git checkout $local_branch
-fi
+		local remote_branch=$(echo $1 | cut -f2- -d":")
+		if [ -z "$remote_branch" ]; then
+			echo "remote_branch not found"
+			exit
+		fi
+
+		local local_branch="${user}/${remote_branch}"
+		if [ $# -ge 2 ]; then
+			local_branch=$2
+		fi
+
+		git fetch $git_url:$user/$git_repo $remote_branch:$local_branch
+		git checkout $local_branch
+	fi
+}
+
+main "$@"
